### ISSUE TITLE
[FR] replace print with assert

### ISSUE THREAD

**Issue by blaggacao** [OCA/pylint-odoo#251]
I'd suggest implementing a checker suggesting
to replace `print` statements with `asserts`.

Where `asserts` are no semantical substitutes for
`print` statements, logging is.

**Comment by moylop260** [comment]
Sorry, I didn't get you

Currently, running the following command:
`python3.7 -m pylint -d all -e print-used --load-plugins=pylint_odoo pylint_odoo/test_repo`

The output is:
pylint_odoo/test_repo/test_module/except_pass.py:20:12: W8116: Print used. Use `logger` instead. (print-used)

What do you want change here?

**Comment by blaggacao** [comment]
`W8116: Print used. Use ``logger`` instead. (print-used)`
->
`W8116: Print used. Use ``logger``or ``asser`` instead. (print-used)`

**Comment by moylop260** [comment]
Using `assert` you will have a `AssertionError`.
IMHO if you like raise a error you should use `raise odoo.exceptions.ANYONEHERE(_('msg of error'))`

This `print-used` check just avoid using `print` in order to avoid showing a `stdout` in the terminal even if you have disabled a log-level.

If you want print a message you should use a logger where we can silent it.

I think assert are another matter here.

Maybe I'm wrong let's wait another opinion here.

@pedrobaeza @Yajo 
What do you think here?

**Comment by pedrobaeza** [comment]
:-1: for me. `assert` is another thing. For outputting any text, use `logger`.

**Comment by blaggacao** [comment]
> If you want print a message you should use a logger where we can silent it.

I guess the OP's argument is that if people say logger, t is their expressed intent. Their real intent however is to assert assumptions about the state of the world.

Asserting state is the evolution of just looking at it, so in most occasions assert is a functional substitute for print, isn't it? - If the person intent was to log something for log analysis, she had used a logger anyhow (because the conscientious intent is logging).

**Comment by blaggacao** [comment]
Consequential of this argument, if your assertion was false, you start to develop a better view assessing the state of the world, which is the second evolution after starting to assert rather than look.

So yes, the `AssertionError` (only rendered during dev time) is for the developer only and shouts: **think harder!!**

**Comment by blaggacao** [comment]
I'll leave it to you to decide if this is too precise / concise or if the current generalization yields superior outcomes.

**Comment by pedrobaeza** [comment]
As upstream code doesn't use your OP logic, it's useless to try to change it on third-party modules, so I still stick to this linter as print only.

**Comment by moylop260** [comment]
>  only rendered during dev time

If you are during dev time then you can change using assert or logger or whatever.
Really, lints are valid just for when you finish your dev time.

It is like `pdb` check.
You can use it for dev time but you will need remove it after that.

If you have a PR using `print` then you will need remove it
We can't request change for a PR with print, using an assert since that a print is not raising an error, it is just printing information.
And logger is "printing" information too.
Considering that creating a PR the dev time is finished.

**Comment by blaggacao** [comment]
> Really, lints are valid just for when you finish your dev time.

The argument still doesn't feel like it has been understood :smile: 

In theory, asserts never hit and are always true. They are not even present during interpretation if 
 (properly) done with `PYTHONOPTIMIZE`. Odoo not using `PYTHONOPTIMIZE` is an odoo specific unvested non-practice (not a big deal, though).

Therefore asserts are genuine transformational susbstitutes for prints / logs *at dev time* and encourage a more concise view of the code (over time).

If the goal was for inters to help the developer do the right thing, then this argument is perfectly valid. If this is a non goal, then this argument is off topic.

**Comment by blaggacao** [comment]
You can look at asserts also as precursor of a type system, which is the most obvious design flaw of Odoo: lack of a strong type system.

**Comment by blaggacao** [comment]
> As upstream code doesn't use your OP logic, it's useless to try to change it on third-party modules, so I still stick to this linter as print only.

Do you mean it's pylint iteself... Hahaha, then this discussion should take place over there... :stuck_out_tongue_winking_eye:
