### ISSUE TITLE
External dependency checks: support distribution library name

### ISSUE THREAD

**Issue by guewen** [OCA/pylint-odoo#264]
A similar check than https://github.com/odoo/odoo/pull/25549 should be added in 
https://github.com/OCA/pylint-odoo/blob/d8bf90dafc1038c602c52608007f3ef433241d7c/pylint_odoo/checkers/modules_odoo.py#L379-L380

_Originally posted by @guewen in https://github.com/OCA/pylint-odoo/pull/263#issuecomment-542623120_

**Comment by guewen** [comment]
From https://github.com/OCA/pylint-odoo/pull/263#issuecomment-542614135

**Comment by moylop260** [comment]
How we can detect the library defined vs package imported? (Since that even it is not the same name)

**Comment by rousseldenis** [comment]
@guewen @moylop260 Is it planned to integrate this soon ?

**Comment by moylop260** [comment]
No, it is not planned to integrate it since that there is not a easy way to match the name of the package vs the imported library

e.g. `pyldap` is the name of the package but imported as `import ldap`


In fact, the reason to use the name of the package in the `__manifest__` has the same focus since that it could be used to install the dependencies because of the old name of `ldap` was not possible to know the name of the package to install

I agree using the package in the manifest but the lint to check a missing dependency could be deprecated if we don't find a easy way to match them
