### ISSUE TITLE
Missing external dependency: Wrong error detected.

### ISSUE THREAD

**Issue by rousseldenis** [OCA/pylint-odoo#295]
https://travis-ci.com/github/shopinvader/odoo-shopinvader/jobs/381147478#L321

It seems that this error is a false positive. I solved it by adding an try/except ImportError during the import:

https://github.com/shopinvader/odoo-shopinvader/pull/713/commits/68de71b43e87b4c37d7cfab46f63e79c93bbadf5#diff-bf0b456c36666d1f67bfb1038653ecc0R17

 The external_dependency was already present.

**Comment by pedrobaeza** [comment]
Are you using latest pylint-odoo version?

**Comment by rousseldenis** [comment]
3.1.0

**Comment by pedrobaeza** [comment]
Uhm, not sure what's happening then. Any tip, @moylop260 ?

**Comment by moylop260** [comment]
Hi @rousseldenis 
Are you talking about the following PR?
 - https://github.com/shopinvader/odoo-shopinvader/pull/619

Because its build is green:
 - https://travis-ci.com/github/shopinvader/odoo-shopinvader/jobs/381203126

You are not using the same sha and its build.

I mean, you are using in the description the following sha:
 - https://github.com/shopinvader/odoo-shopinvader/commit/68de71b43e87b4c37d7cfab46f63e79c93bbadf5

But the URL of the red build is:
 - https://travis-ci.com/github/shopinvader/odoo-shopinvader/jobs/381147478#L321

And it is using the following sha:
 - https://github.com/shopinvader/odoo-shopinvader/commit/d42e4445d692623020f29c31bfd20a11b080a47a
