### ISSUE TITLE
Odoo pylint doesn't respect -disable

### ISSUE THREAD

**Issue by Yenthe666** [OCA/pylint-odoo#298]
Pylint by default has the option to disable some types of checks (see https://stackoverflow.com/questions/3125333/disable-all-pylint-convention-messages/3125349#3125349). 
For example to ignore conventions:
```
pylint --load-plugins=pylint_odoo --disable=C -e odoolint -f json /Yenthe666/auto_backup/14.0/auto_backup/
```

However the pylint-odoo plugin doesn't seem to respect this? If you run it on my `auto_backup` module from https://github.com/Yenthe666/auto_backup.git you can see it in action:
```
[
    // Removed a lot of non-important warnings
    {
        "type": "convention",
        "module": "auto_backup.models.__init__",
        "obj": "",
        "line": 1,
        "column": 0,
        "path": "/Yenthe666/auto_backup/14.0/auto_backup/models/__init__.py",
        "symbol": "unnecessary-utf8-coding-comment",
        "message": "UTF-8 coding is not necessary",
        "message-id": "C8202"
    }
]

```

**Comment by moylop260** [comment]
The order of the disable and enable parameter is important

For your case your using
 - `... --disable=C -e odoolint ...`

It means, disable=C but now enable all odoolint (including the C disabled previously)

You need to change the order to:
 - `... -e odoolint --disable=C ...`

In order to enable all odoolint checks but disabling C ones

I just tested using :

pylint 2.6.0
astroid 2.5
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08)

And last pylint-odoo version

Check the following example:
 - `pylint --load-plugins=pylint_odoo /tmp/auto_backup/auto_backup/ -d C -e odoolint |grep -i utf`
   - `/tmp/auto_backup/auto_backup/__manifest__.py:1:0: C8202: UTF-8 coding is not necessary (unnecessary-utf8-coding-comment)`

 - `pylint --load-plugins=pylint_odoo /tmp/auto_backup/auto_backup/ -e odoolint -d C |grep -i utf`
   - (empty output)
