### ISSUE TITLE
Validate method call inside t-foreach loop

### ISSUE THREAD

**Issue by oscarolar** [OCA/pylint-odoo#299]
Validate if a method that always returns the same result is called inside a `t-foreach` loop to avoid unnecessary method calls and performance issues.

This is an obvious thing for some experienced programmers but not for the newbies, here is an example of what should't be done

```xml
<t t-foreach="attributes" t-as="attribute">
    <t t-set="so" t-value="request.website.sale_get_order()"/>
    #
    # do something with the so variable.
    #
</t>     
```

what to do:
```xml
<t t-set="so" t-value="request.website.sale_get_order()"/>
<t t-foreach="attributes" t-as="attribute">
    #
    # do something with the so variable.
    #
</t>     
```

The conditions that the lint should met are:

- The method call is inside a `t-foreach` loop
- The method call doesn't receive any argument
- The method is not called with a special context and the context has some value as an arg `_with_context(somevalue)`

**Comment by moylop260** [comment]
It is a good check

But it is hard to make this check from pylint

Since that it is using a combination of many languages python, xml, html, js, qweb

QWeb is a custom Odoo parser xml2python:
 - https://github.com/odoo/odoo/blob/38983d123d171ac3cc1efacd99d9776f0ed08734/odoo/addons/base/models/qweb.py#L1151

It could require transform it to astroid/pylint format but it is not an easy way to do

Feel free to re-open or discuss it
