### ISSUE TITLE
New release this week for odoo 15 tooling?

### ISSUE THREAD

**Issue by Yajo** [OCA/pylint-odoo#352]
If you push a new release, I can tag it for .pre-commit-config when preparing the template for Odoo 15. See https://github.com/OCA/oca-addons-repo-template/issues/69

cc @moylop260 @sbidoul

**Comment by moylop260** [comment]
Hi @Yajo 

Good point!
Thank you

I just merged the following new future 15.0 version as valid-odoo-version:
 - https://github.com/OCA/pylint-odoo/pull/353

And I just merged a PR related with sql-injection

I just released the pylint-odoo 5.0.1
 - https://pypi.org/project/pylint-odoo/5.0.1

**Comment by moylop260** [comment]
For record, since that the pylint configuration file is using the following option:
  - [valid_odoo_versions={{ odoo_version }}](https://github.com/OCA/oca-addons-repo-template/blob/2c2714cfaac805d9eebd98a401b73420744d660c/src/.pylintrc-mandatory.jinja#L11) it will use the new Odoo version valid for that branch

So, a new release is not required but better using the latest changes

**Comment by moylop260** [comment]
Wait... let me bump the latest versions of `pylint` too

**Comment by moylop260** [comment]
...done

https://pypi.org/project/pylint-odoo/5.0.2

**Comment by Yajo** [comment]
Thanks, changed in template.
