### ISSUE TITLE
Disable api-one-deprecated for new odoo comments

### ISSUE THREAD

**Issue by moylop260** [OCA/pylint-odoo#45]
Odoo recommend us not using `api.one`: https://github.com/odoo/odoo/pull/8527
After odoo use `api.one` in v9: https://github.com/odoo/odoo/commit/8ac40acb0d9a234eb59e55c3bc8f1a9a75bc4469
A issue for this case was created: https://github.com/odoo/odoo/issues/12408

Odoo answer: https://github.com/odoo/odoo/issues/12408#issuecomment-226421501

The question is: Should we disable the check `api-one-deprecated`?

**Comment by aristobulo-eezee** [comment]
Well as Olivier Dony explained, that decorator is useful in some particular cases, but is not recommended to be used on methods that will `return` values. And as you might noticed, they are `api.one` on v10, so, use it.

I don't know if you could check if the method has a `return` statement and in that case raise a failure, I mean, at least you could enforce a proper use of this.

Although, if you want to think about it, it should be renamed to `api.schrodinger` because is recommended and deprecated at the same time 😅

(not) Sorry for the bad joke.

**Comment by dreispt** [comment]
This is a rollercoater...
IMO `api.one` makes code better.
I wish there was a clearer confirmation from @odony that it is not deprecated anymore, and is not expected to be removed from the API.

We can keep the check in pylint-odoo, but it should be disabled by default.

**Comment by moylop260** [comment]
Ok
Then I could let enabled from `pylint-odoo` and disable from MQT, right?

**Comment by dreispt** [comment]
@moylop260 Yes: keep it in pylint, but disable it in the MQT checks.

**Comment by lasley** [comment]
IMO `api.one` comes with some other potential issues that aren't described there. Admittedly I don't fully understand the cache + ORM, but the below is an anti-pattern enforced by this API that I see quite often - it feels very much like n+1:

```
@api.one
def one_meth(self):
    self.multi_meth()

@api.multi
def multi_meth(self):
    # Do some stuff
    self.write(vals)
```

**Comment by pedrobaeza** [comment]
@lasley, for most of the operations, they are cached, so no performance loss in that cases. Anyway, it's developer responsibility to make an appropriated call stack.

**Comment by dreispt** [comment]
@lasley All I know is that fetched objects are cached a«until invalidated. AFAICS both examples you give are equivalent performance wise. 
But the first is more succinct and expressive than the second, that is also error prone (forgetting to loop on self).

**Comment by lasley** [comment]
Ahhh cool now that I'm looking at the code, I see the recordset fetch before the loop too. My bad, I probably should have looked there before spouting my mouth 😛 

I feel like this is still deprecated though. IMO the code doc blocks seem to be the most accurate source of info in Odoo, and it very clearly says [deprecated in 9](https://github.com/odoo/odoo/blob/9.0/openerp/api.py#L405). 

Odoo SA literally said "shit happens, we ship bad code", which to me means this feature could be removed almost overnight with a planned project of their's we have no idea about. I believe that until they update some sort of official something, we should be adhering to the deprecation warnings.

**Comment by pedrobaeza** [comment]
Well, I'll try to comment directly with them on October for the Odoo days and see. Are you coming?

**Comment by lasley** [comment]
I didn't even know this was a thing - I'll see if I can get some travel plans arranged. Belgium is on the list of places I need to see in my life anyways, so it's like a two-fer! 😄 

It would be nice to be at a conference where people know what Odoo is lol I represented at PyCon and got a lot of blank stares & comments about Plone 😑

**Comment by elicoidal** [comment]
Couldnot we turn the message into a simple warning in the mean time?

**Comment by lasley** [comment]
Seems like I might be outnumbered here but I would consider all information obtained at this point to be hearsay that directly conflicts with both documentation and code doc blocks - both of which align. IMO a CI should error out on all explicit deprecations, which I interpret this as being.

**Comment by dreispt** [comment]
@lasley You're right when you say that docs state it as deprecated. But then go and read this: https://github.com/odoo/odoo/issues/12408#issuecomment-226421501
It seems that it can be de-deprecated 😆

**Comment by lasley** [comment]
I dunno though- he says maybe they should rethink the way the docs are written, but no definitive action has been taken in this regard. This was one person's opinion and while I would say it definitely holds way more weight than if someone like me said it, the point remains that the docs have not been updated and this ticket was closed with no action.

I would say we should open an issue with Odoo SA at least for definitive clarification or documentation update, but I have had horrible luck with anything like that and avoid PRs/Issues in their repo like the plague 😑 

I won't block if was can keep it as a warning like @elicoidal suggested so that I can continue to remove in my own code, but this really just scares me drawing from past experiences with deprecation warnings in other libraries. Then again, maybe Odoo is different and has a history of this whole de-deprecation without doc updates thing & I am just being overly cautious.

**Comment by dreispt** [comment]
@lasley I agree that we shouldn't change until we have confirmation from Odoo people.

**Comment by Yajo** [comment]
How about sending them a docs PR that documents it better and undeprecates it?

**Comment by aristobulo-eezee** [comment]
@Yajo I had the chance to talk with them about this, it was very clear that they do not plan to deprecate `api.one` and they were just waiting to merge this update into the docs. Yes, maybe using the MR approach will be faster than just waiting.

**Comment by Yajo** [comment]
Then I'm going to do it right now, let's see if giving them the simplicity of fixing this by pressing one button makes this get closed definitely.

**Comment by Yajo** [comment]
Done. https://github.com/odoo/odoo/pull/13199

**Comment by dreispt** [comment]
@Yajo that's the spirit 😄

**Comment by pedrobaeza** [comment]
Closing as it has been finally decided to continue the deprecation
