### ISSUE TITLE
Warn/Error on use of fields_view_get in linting Odoo v16.

### ISSUE THREAD

**Issue by gdgellatly** [OCA/pylint-odoo#469]
**Is your feature request related to a problem?**
In v16 `fields_view_get` and associated methods are deprecated. This means that any module that is overriding it is not called. I got caught in a private module migration, but a grep shows that these have been passing through OCA review without question.

**Describe the solution you'd like**
A warning with recommendation to use `get_view`  or `_get_view` as appropriate.

Also note, while the arguments are basically the same, the results of get view are a little different to the old fields_view_get, returning a single arch and no dict of subviews.

**Comment by moylop260** [comment]
@antonag32 

Could you create a generic lint check to detect deprecated odoo function definition, please?

It should be configured from `self.linter.config` by default `fields_view_get`

Also, checks if the class node has `"Model"` in its `basenames` in order to get only function definition of Odoo classes
