### ISSUE TITLE
REQUEST: Checker for Odoo warning "The model {model_name} has no _description"

### ISSUE THREAD

**Issue by espo-tony** [OCA/pylint-odoo#482]
Hi,

Odoo throws a WARNING if a model is defined with no `_description` attribute.
It would be nice to have a checker for this as well.

**Comment by antonag32** [comment]
For reference, `_description` is only required if the class defines a `_name` attribute which means a new model is being declared. Am I missing some other cases @luisg123v ?

**Comment by espo-tony** [comment]
@antonag32 
Correct: `_description` is only required when a new model is being declared.
This is when the class defines a `_name` attribute and that `_name` is not in the `_inherit` attribute.

**Comment by luisg123v** [comment]
Hi,

Not sure if this would be possible. What about if it's an inherited model and the model name is not in the `_description` attribute? That's a valid model declaration AFAIK and it would be detected as a new model.

On the other hand, since it's already covered by Odoo, I wouldn't consider it as important.

Regards,
